# Refer to https://github.com/marketplace/actions/rust-release-binary for more info
on:
  release:
    types:
      - published

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@master

      - name: Set version
        run: ./set_version.sh

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build'
        run: |
          docker build -t pgav .

      - name: 'tag and push to ghcr.io'
        run: |
          for TAG in latest ${{ github.ref_name }}; do
            docker tag pgav ghcr.io/mannemsolutions/pgav:${TAG}
            docker push ghcr.io/mannemsolutions/pgav:${TAG}
          done
