# Refer to https://github.com/marketplace/actions/rust-release-binary for more info
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_binaries:
    name: Build and push binaries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@v4
      - name: Set version
        run: ./set_version.sh
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo build -r --platform ${{ matrix.arch }}-unknown-linux-musl
          tar -acvf pgav_linux_${{ matrix.arch }}.tar.gz README.md LICENSE -C target/release pgav

      - name: Add to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pgav_linux_${{ matrix.aarch }}.tar.gz
            README.md
            LICENSE
